DROP TABLE IF EXISTS BUSINESS;
DROP TABLE IF EXISTS PRIVATE;
DROP TABLE IF EXISTS REQUESTS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS PRIORITY;
DROP TABLE IF EXISTS RSTATUS;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS CSTATUS;

DROP SEQUENCE IF EXISTS priority_seq;
DROP SEQUENCE IF EXISTS rstatus_seq;
DROP SEQUENCE IF EXISTS cstatus_seq;


/*DROP SCHEMA public CASCADE;
CREATE SCHEMA public;*/