DROP TABLE IF EXISTS BUSINESS CASCADE;
DROP TABLE IF EXISTS PRIVATE CASCADE;
DROP TABLE IF EXISTS TRANSACTIONS CASCADE;
DROP TABLE IF EXISTS REQUESTS CASCADE;
DROP TABLE IF EXISTS PRODUCTS CASCADE;
DROP TABLE IF EXISTS PRIORITY CASCADE;
DROP TABLE IF EXISTS RSTATUS CASCADE;
DROP TABLE IF EXISTS EMPLOYEE CASCADE;
DROP TABLE IF EXISTS CUSTOMERS CASCADE;
DROP TABLE IF EXISTS CSTATUS CASCADE;

DROP SEQUENCE IF EXISTS priority_seq CASCADE;
DROP SEQUENCE IF EXISTS rstatus_seq CASCADE;
DROP SEQUENCE IF EXISTS cstatus_seq CASCADE;